# Generated by Django 3.2.7 on 2021-09-12 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0002_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30')], default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car_num',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 1 letter, and 1 to 6 nums', regex='^[A-Za-z][0-9]{1,6}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('user', 'timeslot')},
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
