# Generated by Django 3.2.7 on 2021-09-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0004_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.IntegerField(choices=[(None, 'الأيام'), (0, 'الأثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء')], default=None),
        ),
    ]
