# Generated by Django 3.2.7 on 2021-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0008_alter_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
