# Generated by Django 3.2.7 on 2021-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0009_alter_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(None, 'الأوقات'), (0, '08:30 – 09:00'), (1, '09:00 – 09:30'), (2, '09:30 – 10:00'), (3, '10:00 – 10:30'), (4, '10:30 – 11:00'), (5, '11:00 – 11:30'), (6, '11:30 – 12:00'), (7, '12:00 – 12:30'), (8, '12:30 – 01:00'), (9, '01:00 – 01:30'), ('a', '01:30 – 02:00'), ('b', '02:00 – 02:30'), ('c', '02:30 – 03:00'), ('d', '03:00 – 03:30')], default=None),
        ),
    ]
