# Generated by Django 3.2.7 on 2021-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0010_alter_appointment_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
