# Generated by Django 3.2.7 on 2021-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0011_appointment_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(None, 'الأوقات'), (0, '08:30 – 09:00'), (10, '09:00 – 09:30'), (11, '09:30 – 10:00'), (12, '10:00 – 10:30'), (13, '10:30 – 11:00'), (14, '11:00 – 11:30'), (15, '11:30 – 12:00'), (16, '12:00 – 12:30'), (17, '12:30 – 01:00'), (18, '01:00 – 01:30'), (19, '01:30 – 02:00'), (20, '02:00 – 02:30'), (21, '02:30 – 03:00'), (22, '03:00 – 03:30')], default=None),
        ),
    ]
