# Generated by Django 3.2.7 on 2021-09-21 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0012_alter_appointment_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='must be 8 numbers for example: 03-xxxxxx', regex='^[0-9]{2}-[0-9]{6}')]),
        ),
    ]
