# Generated by Django 3.2.7 on 2021-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_q', '0013_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.IntegerField(choices=[(None, 'الأوقات'), (10, '08:30 – 09:00'), (11, '09:00 – 09:30'), (12, '09:30 – 10:00'), (13, '10:00 – 10:30'), (14, '10:30 – 11:00'), (15, '11:00 – 11:30'), (16, '11:30 – 12:00'), (17, '12:00 – 12:30'), (18, '12:30 – 01:00'), (19, '01:00 – 01:30'), (20, '01:30 – 02:00'), (21, '02:00 – 02:30'), (22, '02:30 – 03:00'), (23, '03:00 – 03:30')], default=None),
        ),
    ]
